# Generated by Django 5.2.7 on 2025-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Product color like Red, Blue, Gold', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('saree', 'Saree'), ('kurtis', 'Kurtis'), ('lehengas', 'Lehengas'), ('dresses', 'Dresses'), ('gowns', 'Gowns'), ('kids', 'Kids Wear')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], max_length=10, null=True),
        ),
    ]
