# Generated by Django 5.2.7 on 2025-11-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_product_color_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, help_text='Fabric type like Cotton, Silk, Linen', max_length=120, null=True),
        ),
    ]
