# Generated by Django 5.2.7 on 2025-11-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_product_thumbnail1_product_thumbnail2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_return',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style_fit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
