# Generated by Django 5.2.7 on 2025-11-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_product_shipping_return_product_style_fit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='product_code',
        ),
        migrations.AddField(
            model_name='product',
            name='allow_coupons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
