# Generated by Django 5.2.7 on 2025-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_coupon_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
