# Generated by Django 5.2.7 on 2025-11-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customercoupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCoupon',
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
