# Generated by Django 5.2.7 on 2025-11-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_cart_size_orderitem_size_productsizeprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.DeleteModel(
            name='ProductSizePrice',
        ),
    ]
