# Generated by Django 5.2.7 on 2025-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_product_options_remove_cart_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_l',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_xl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_xxl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
