# Generated by Django 5.2.7 on 2025-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_checkoutdetails_paymentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
