# Generated by Django 5.2.7 on 2025-11-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_checkoutdetails_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
