# Generated by Django 5.2.7 on 2025-11-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
