# Generated by Django 5.2.7 on 2025-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_orderitem_size_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
