# Generated by Django 5.2.7 on 2025-11-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_add_checkoutdetails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='category',
            field=models.CharField(blank=True, choices=[('saree', 'Saree'), ('kurtis', 'Kurtis'), ('lehengas', 'Lehengas'), ('dresses', 'Dresses'), ('gowns', 'Gowns'), ('kids', 'Kids Wear')], max_length=50, null=True),
        ),
    ]
