# Generated by Django 5.2.6 on 2025-12-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_merge_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_l',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_s',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_xl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_xxl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
