# Generated by Django 5.2.6 on 2025-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
