# Generated by Django 5.2.6 on 2025-12-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('women', 'Women'), ('kids', 'Kids')], max_length=10)),
                ('image', models.ImageField(upload_to='subcategories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'gender')},
            },
        ),
    ]
