# Generated by Django 5.2.6 on 2025-12-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('fulfilled', 'Order Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
