# Generated by Django 5.2.6 on 2025-12-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_alter_order_status'),
    ]

    operations = [

        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('fulfilled', 'Order Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
