# Generated by Django 5.2.6 on 2026-01-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='US', max_length=100),
        ),
    ]
