# Generated by Django 5.2.6 on 2026-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_order_delivered_at_order_shipped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
