# Generated by Django 5.2.6 on 2026-01-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_order_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada')], default='US', max_length=100),
        ),
    ]
