# Generated by Django 5.2.6 on 2026-01-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('fulfilled', 'Order Fulfilled'), ('cancelled', 'Cancelled'), ('cancelled_by_admin', 'Cancelled by Admin')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('fulfilled', 'Order Fulfilled'), ('cancelled', 'Cancelled'), ('cancelled_by_admin', 'Cancelled by Admin')], max_length=20),
        ),
    ]
