# Generated by Django 5.2.6 on 2026-01-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_order_admin_cancel_reason_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart_type',
            field=models.CharField(choices=[('none', 'No Size Chart'), ('women_general', 'Women - General Size Chart'), ('women_blouse', 'Women - Blouse Size Chart'), ('kids', 'Kids - Size Chart')], default='none', max_length=50),
        ),
    ]
