# Generated by Django 5.2.7 on 2025-11-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_womencoupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WomenCoupon',
        ),
    ]
