# Generated by Django 5.2.6 on 2025-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_delete_womencoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_users', 'Can manage non-admin users'), ('access_analytics', 'Can access analytics dashboards'), ('manage_billing', 'Can manage billing and invoices'), ('content_moderation', 'Can moderate user-generated content')],
            },
        ),
    ]
