# Generated by Django 5.2.6 on 2026-01-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_adminotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('women', 'Women Page'), ('kids', 'Kids Page')], default='home', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Lower number appears first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
