# Generated by Django 5.2.6 on 2026-01-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(upload_to='traditional_looks/')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Lower number appears first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
