# Generated by Django 5.2.6 on 2026-01-12 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_traditionallook'),
        ('customer', '0051_customer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traditionallook',
            name='link',
        ),
        migrations.AddField(
            model_name='traditionallook',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.product'),
        ),
    ]
